"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SafeDepositBox.py']
DATA_FILES = ['S3Sandbox.py',
              'S3BucketPolicy.py',
              'EncryptionService.py',
              'util.py',
              'constants.py']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
